<a href="https://colab.research.google.com/github/Muhammad-Farhan-A/Kelompok-2-APM-B/blob/main/Project_Naive%20Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import library
import numpy as np 
import pandas as pd

In [ ]:
#menampilkan dataset
dataset = pd.read_csv("healthcare-dataset-stroke-data.csv")
dataset

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [ ]:
#melihat informasi dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [ ]:
#menghapus baris data yang tidak memiliki nilai dan mengubah tipe data string menjadi numerik
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
dataset['gender'] = enc.fit_transform(dataset['gender'].values)
dataset['ever_married'] = enc.fit_transform(dataset['ever_married'].values)
dataset['work_type'] = enc.fit_transform(dataset['work_type'].values)
dataset['Residence_type'] = enc.fit_transform(dataset['Residence_type'].values)
dataset['smoking_status'] = enc.fit_transform(dataset['smoking_status'].values)
dataset.dropna()

id  gender   age  hypertension  heart_disease  ever_married  \
0      9046       1  67.0             0              1             1   
2     31112       1  80.0             0              1             1   
3     60182       0  49.0             0              0             1   
4      1665       0  79.0             1              0             1   
5     56669       1  81.0             0              0             1   
...     ...     ...   ...           ...            ...           ...   
5104  14180       0  13.0             0              0             0   
5106  44873       0  81.0             0              0             1   
5107  19723       0  35.0             0              0             1   
5108  37544       1  51.0             0              0             1   
5109  44679       0  44.0             0              0             1   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  \
0             2               1             228.69  36.6               1   
2             2               0             105.92  32.5               2   
3             2               1             171.23  34.4               3   
4             3               0             174.12  24.0               2   
5             2               1             186.21  29.0               1   
...         ...             ...                ...   ...             ...   
5104          4               0             103.08  18.6               0   
5106          3               1             125.20  40.0               2   
5107          3               0              82.99  30.6               2   
5108          2               0             166.29  25.6               1   
5109          0               1              85.28  26.2               0   

      stroke  
0          1  
2          1  
3          1  
4          1  
5          1  
...      ...  
5104       0  
5106       0  
5107       0  
5108       0  
5109       0  

[4909 rows x 12 columns]

In [ ]:
#menghapus kolom yang tidak digunakan serta mengubah tipe data
dataset = dataset.drop(["id", "bmi"], axis = 1)
dataset["age"] = dataset["age"].astype("int")
dataset["avg_glucose_level"] = dataset["avg_glucose_level"].astype("int")
dataset.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'smoking_status',
       'stroke'],
      dtype='object')

In [ ]:
#menentukan variabel independen
x = dataset.drop(['stroke'], axis = 1)
x.head()

gender  age  hypertension  heart_disease  ever_married  work_type  \
0       1   67             0              1             1          2   
1       0   61             0              0             1          3   
2       1   80             0              1             1          2   
3       0   49             0              0             1          2   
4       0   79             1              0             1          3   

   Residence_type  avg_glucose_level  smoking_status  
0               1                228               1  
1               0                202               2  
2               0                105               2  
3               1                171               3  
4               0                174               2

In [ ]:
#menentukan variabel dependen
y = dataset['stroke']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: stroke, dtype: int64

In [ ]:
#split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
#mengaktifkan package dan fungsi gaussian naive bayes
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
#memasukkan data training pada fungsi
nb = model.fit(x_train, y_train)

In [ ]:
#melakukan prediksi
y_pred = nb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#menentukan probabilitas hasil prediksi
nb.predict_proba(x_test)

array([[7.00004290e-01, 2.99995710e-01],
       [9.99999982e-01, 1.79887308e-08],
       [8.85768767e-01, 1.14231233e-01],
       ...,
       [1.00000000e+00, 5.33988543e-11],
       [9.99941354e-01, 5.86461974e-05],
       [9.99999773e-01, 2.27007343e-07]])

In [ ]:
#mengimport classification report dan confusion matrix dari SKlearn
from sklearn.metrics import classification_report, confusion_matrix
#menentukan probabilitas dari prediksi
print(confusion_matrix(y_test, y_pred))

[[867 106]
 [ 29  20]]


In [ ]:
#mengukur ketepatan/keakuratan hasil prediksi
print(classification_report(y_test, y_pred))
print("Gaussian Naive Bayes score: ",nb.score(x_test, y_test))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93       973
           1       0.16      0.41      0.23        49

    accuracy                           0.87      1022
   macro avg       0.56      0.65      0.58      1022
weighted avg       0.93      0.87      0.89      1022

Gaussian Naive Bayes score:  0.8679060665362035
